### PR TITLE
Unhardcode g++

### PR DESCRIPTION
**Pull request by AMDmi3**
C++ compiler is not necessarily g++, which may not exist on the system at all.
This is fix for one of the _many_ problems in this Makefile.

### CODE REVIEW

**Comment by Aaron-SP** [comment]
I'm not super great with makefile syntax so if you just want to leave a list of issues I can fix since I am working on that right now.

Merged in https://github.com/Aaron-SP/bds/commit/d1ac5309590fe0586c9c833589e2ac5480b646a6.

**Comment by AMDmi3** [comment]
Well honestly it would be much easier to implement a proper build system such as CMake. I found it easier to build it with a single `c++` command than fixing the makefile. Still, incomplete list:
- Build should be verbose, so I'd get rid of `2> foo.txt` stuff
- It took me quite some time to figure out the build mode I need, which is seemingly inline-dynamic. It should probably be the default, with `all` target pointing to it. I'd also get rid of `dynamic` mode as it's least convenient: additional step is required to build a library, and then one need to specify LD_LIBRARY_PATH for the game to find it.
- Consider adding mgl as a submodule to the game repository. This way you'll be able to get rid of MGL_PATH which assumes that mgl is fetched separately and installed either to hardcoded location or systemwide, which is never the case
- Using `-march=native` is not packaging-friendly (as it will make the binary tied to build machine architecture and package will not work on other machines). Better to remove it from RELEASE flags
- Why don't you use system GLEW?
- Installation is beyond non-standard. The usual way is like this:
```
PREFIX?=/usr/local
install:
    install -d <binary> $(DESTDIR)$(PREFIX)/bin
    mkdir -p $(DESTDIR)$(PREFIX)/share/bds
    cp -rv <data> $(DESTDIR)$(PREFIX)/share/bds
    install -d <desktopfile> $(DESTDIR)$(PREFIX)/share/applications
```
Note that DESTDIR is empty by default; it's used for staging, e.g. when you want to install the game into temporary location (instead of live filesystem) and make a system package out of it.
Also note that install -d will create directories automatically
- When installation is fixed, you can add e.g. `-DDATA_PATH="\"$(PREFIX)/share/bds\""` to compiler flags to make the game know where its data is stored, and avoid the need for a shell wrapper
- Save files in data directory and 777 permissions are obviously not an option. Consider storing them in the dotdir (`${HOME}/.bds`), or better conform to [XDG specification](https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html), e.g. use `${XDG_DATA_DIR}/bds/save`, if XDG_DATA_DIR is specified otherwise `${HOME}/.local/share/bds/save`

**Comment by Aaron-SP** [comment]
Perhaps creating a more standard Unix installer should be the next move. I am still finding critical bugs in the code and I need something that let's me tinker with the build process easily.

> Why don't you use system GLEW?

I could drop including the bundled GLEW for Unix systems. I'll do this.

> -march=native

I fixed this.
- You can set the BUILD flag with arch32, arch64, and debug else defaults to native.

> Consider storing them in the dotdir (${HOME}/.bds)

I will do this soon.

**Comment by Aaron-SP** [comment]
I've tried to address these issues in https://github.com/Aaron-SP/bds/commit/d3f582ac183c29ec36fafd3cbedd38df09e06b2e.

- [x] Use system GLEw
- [x] Allow building other than -march=native
- [x] 2> foo.txt stuff removed
- [x] Saves files into $(HOME)/.bds-game, path is currently captured at compile time which needs to be updated to environment variables.
- [x] Install game binary to /usr/local/bin
- [x] Install data folder into /usr/local/share/bds
- [x] inline-dynamic default build target at `make all`

**Pull request closed without merging**
